name: My GitHub Action

on: push  # This triggers the action when you push a commit

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 24ds300032@ds.study.iitm.ac.in  # Your email (as required)
        run: echo "Hello, world!"
